### ISSUE TITLE
password for VNC

### ISSUE THREAD

**Issue by sealabr** [BenSchZA/docker-android-avd#3]
Hello, when access the url localhost:6080, this url ask the password.

where I can get the password? thanks.

**Comment by sealabr** [comment]
![image](https://user-images.githubusercontent.com/21187479/66395486-e4dfd880-e9ad-11e9-895a-81cc59b9550f.png)

**Comment by BenSchZA** [comment]
Hey @sealabr ! I don't remember there being a password, but I'll give it a try and let you know. Perhaps one of the Docker image dependencies was updated.

**Comment by sealabr** [comment]
found the passoword: secret

**Comment by BenSchZA** [comment]
Thanks @sealabr . I'll add this to the README. Going to re-open to remind me.

**Comment by pizzapim** [comment]
I'm also getting a username and password prompt. There the credentials are root:secret.

**Comment by BenSchZA** [comment]
Thanks @pizzapim ! Just added it to the README.
